#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

wclean

wclean rhoReactionThermo
rm -f rhoReactionThermo/rhoReactionThermo*.*

#------------------------------------------------------------------------------
