#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Set environment variables
. etc/bashrc

# Compile catchyFOAM libraries
src/Allwmake

# Compile catchyFOAM solvers
applications/solvers/Allwmake

# Compile catchyFOAM utilities
applications/utilities/Allwmake

# Compile CFDEMcoupling libraries and solvers
source CFDEM/CFDEMcoupling/etc/bashrc
bash CFDEM/CFDEMcoupling/etc/compileCFDEMcoupling_all.sh

#------------------------------------------------------------------------------
